//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yapay_Zeka_Projesi_Arayüzü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analizler
    {
        public int Ornekid { get; set; }
        public string Ad { get; set; }
        public string ResimUrl { get; set; }
        public string ModelAd { get; set; }
        public string ModelResimUrl { get; set; }
        public string ModelYemekAdi { get; set; }
        public string ModelIcindekiler { get; set; }
        public Nullable<decimal> ModelMiktar { get; set; }
        public Nullable<decimal> ModelProtein { get; set; }
        public Nullable<decimal> ModelKarbonhidrat { get; set; }
        public Nullable<decimal> ModelKalori { get; set; }
    }
}
