//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yapay_Zeka_Projesi_Arayüzü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anasayfa
    {
        public int Anasayfaid { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string ButtonYazi { get; set; }
        public string ButtonUrl { get; set; }
    }
}
