//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yapay_Zeka_Projesi_Arayüzü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ekip
    {
        public int KisiId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Title { get; set; }
        public string ResimUrl { get; set; }
    }
}
