//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yapay_Zeka_Projesi_Arayüzü.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YzprojesiEntities : DbContext
    {
        public YzprojesiEntities()
            : base("name=YzprojesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anasayfa> Anasayfa { get; set; }
        public virtual DbSet<Hizmetler> Hizmetler { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Ekip> Ekip { get; set; }
        public virtual DbSet<Analizler> Analizler { get; set; }
    }
}
